export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_GITHUB = 'LOGIN_GITHUB';

export const SET_COUNTER = 'SET_COUNTER';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const REPOS_GET = 'REPOS_GET';
export const REPO_SELECTED = 'REPO_SELECTED';
export const REPOS_GET_REQUEST = 'REPOS_GET_REQUEST';
export const REPOS_GET_SUCCESS = 'REPOS_GET_SUCCESS';
export const REPOS_GET_FAILURE = 'REPOS_GET_FAILURE';

export const LOCATION_RECEIVED = 'LOCATION_RECEIVED';
